#!/usr/bin/env python3
"""Independent generator for QwenChess Zobrist key fixtures.

This is a TEST-FIXTURE generator only (not part of the shipped engine; the C
tests use checked-in constants and need no Python at run time). It replicates the
documented SplitMix64 generation of src/core/zobrist.c INDEPENDENTLY, using the
same documented seed and draw order, with explicit modulo-2**64 arithmetic.

Generation (must mirror src/core/zobrist.c zobrist_init exactly):
  state = ZOB_SEED = 0x9E3779B97F4A7C15   (the 64-bit golden-ratio constant)
  each value = splitmix64(state):
        state = (state + 0x9E3779B97F4A7C15) mod 2**64
        z = state
        z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9 mod 2**64
        z = (z ^ (z >> 27)) * 0x94D049BB133111EB mod 2**64
        return z ^ (z >> 31)
  draw order:
    1. piece-square keys: for rank 0..7, file 0..7, piece 0..15  (1024 draws)
       -> g_piece[piece][square], square = rank*8+file (square-major)
    2. g_side[BLACK] = 1 draw      (g_side[WHITE] is fixed to 0, no draw)
    3. g_castling[0..15]           (16 draws)
    4. g_epfile[0..7]              (8 draws)
  Total: 1024 + 1 + 16 + 8 = 1049 values.

Run:  python3 tools/zobrist_gen.py
Emits C `u64` initializer lines to paste into tests/zobrist_test.c.
"""

MASK = (1 << 64) - 1
INC  = 0x9E3779B97F4A7C15   # == ZOB_SEED, and the splitmix64 increment
M1   = 0xBF58476D1CE4E5B9
M2   = 0x94D049BB133111EB

_state = INC


def sm64() -> int:
    """Advance the shared state and return the next SplitMix64 value."""
    global _state
    _state = (_state + INC) & MASK
    z = _state
    z = ((z ^ (z >> 30)) * M1) & MASK
    z = ((z ^ (z >> 27)) * M2) & MASK
    return (z ^ (z >> 31)) & MASK


def main() -> None:
    global _state
    _state = INC

    # 1. piece-square keys, square-major, piece 0..15 per square
    piece = [[0] * 64 for _ in range(16)]
    for r in range(8):
        for f in range(8):
            s = (r << 3) | f
            for p in range(16):
                piece[p][s] = sm64()

    side_black = sm64()
    castling = [sm64() for _ in range(16)]
    epfile = [sm64() for _ in range(8)]

    a1 = [piece[p][0] for p in range(16)]     # g_piece[0..15][0]
    h8 = [piece[p][63] for p in range(16)]    # g_piece[0..15][63]

    def hexarr(vals):
        return ", ".join("0x%016Xull" % v for v in vals)

    print("/* generated by tools/zobrist_gen.py ; seed 0x9E3779B97F4A7C15 (ZOB_SEED) */")
    print("/* order: 1024 piece-square (square-major, p=0..15) + 1 black side + 16 castling + 8 ep-file */")
    print("static const u64 P_A1[16]   = { %s };" % hexarr(a1))
    print("static const u64 P_H8[16]   = { %s };" % hexarr(h8))
    print("static const u64 SIDE_BLACK = 0x%016Xull;" % side_black)
    print("static const u64 CASTLE[16] = { %s };" % hexarr(castling))
    print("static const u64 EPFILE[8]  = { %s };" % hexarr(epfile))
    # human-readable anchors for the record
    print("# anchors: first piece draw g_piece[0][0]=0x%016X ; last g_piece[15][63]=0x%016X"
          % (piece[0][0], piece[15][63]))
    print("#           g_side[BLACK]=0x%016X g_castling[0]=0x%016X g_epfile[7]=0x%016X"
          % (side_black, castling[0], epfile[7]))


if __name__ == "__main__":
    main()
